name: 'Setup Atom'
description: 'Setup Atom and APM'
inputs:
  version:
    description: 'Version, defaults to "stable"'
    required: false
    default: 'stable'
  token:
    description: 'GitHub token with read permission for finding stable and beta versions, defaults to secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'green'
