name: 'Setup Atom'
description: 'Setup Atom and APM'
inputs:
  channel:
    description: 'Channel'
    required: true
    default: 'Stable'
  packageManager:
    description: 'If provided, this package manager will be used to install Atom instead of downloading the official releases.'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'green'
